Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/riddles/urls.py
from django.conf.urls import url

from . import views

app_name = 'riddles'

urlpatterns = [
    url(r'^$', views.riddles, name='riddles'),
    url('(?P<plane_id>\d+)', views.air_detail, name='air_detail_url'),
    url('fly/', views.fly_list, name='fly_list_url'),
    url('(?P<fly_id>\d+)', views.fly_detail, name='fly_detail_url')

]

Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/untitled1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^riddles/', include('riddles.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
]

Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/riddles/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
class plane(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField(max_length=128, unique=True)
    type = models.CharField(max_length=128)
    flys = models.ManyToManyField('fly', related_name='planes')


def get_absolute_url(self):
    return reverse('air_detail_url', kwargs={'slug': self.slug})


def __str__(self):
    return self.name


class fly(models.Model):
    time = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.time)

Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/riddles/forms.py
from django.forms import ModelForm
from .models import *


class PlaneForm(ModelForm):
    class Meta:
        model = plane
        #fields
        exclude = [""]

Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/riddles/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render
from .forms import PlaneForm
from .models import plane, fly
from django.shortcuts import get_object_or_404


def riddles(request):
    form = PlaneForm(request.POST or None)
    n = ['Лол', ' кек', ' чебурек']
    planes = plane.objects.all()
    return render(request, 'riddles/riddles.html', {'form': form,
                                                    'lol': n,
                                                    'planes': planes})


def air_detail(request, plane_id):
    # air = plane.objects.get(id__iexact=plane_id)
    air = get_object_or_404(plane, id__iexact=plane_id)
    return render(request, 'riddles/air_detail.html', {'air': air})


def fly_list(request):
    flys = fly.objects.all()
    return render(request, 'riddles/fly_list.html', context={'flys': flys})


def fly_detail(request, fly_id):
    # flyy = fly.objects.get(id__iexact=fly_id)
    flyy = get_object_or_404(fly, id__iexact=fly_id)
    return render(request, 'riddles/fly_detail.html', {'fly': flyy})

Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/templates/riddles/air_detail.html
{% extends 'riddles/pattern.html' %}

{% block title %}
    Аэропорт {{ air.name }} - {{ block.super }}
{% endblock %}

    {% block header %}
         Аэропорт {{ air.name }}
    {% endblock %}

{% block content %}
    <h3>
    Расписание:
    </h3>

    <p>
    {{ air.type }}
    {% for fly in air.flys.all %}
        <li>
         {{ fly.id }}
        {{ fly.time }}

        </li>

    {% endfor %}

    </p>

{% endblock %}

Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/templates/riddles/fly_detail.html
{% extends 'riddles/pattern.html' %}
{% block title %}
    Рейс {{ fly.id }}
{% endblock %}
{% block header %}
    Рейс {{ fly.id }}
{% endblock %}
{% block content %}
    <p>
    Время вылета: {{ fly.time }}
    {% for plane in fly.planes.all %}
    <p>
    <h2>
    {{ plane.name }}
    </h2>
        {{ plane.type }}
    </p>
    {% endfor %}

    </p>
{% endblock %}

Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/templates/riddles/fly_list.html
{% extends 'riddles/pattern.html' %}

{% block title %}
    Flies list
{% endblock %}

{% block header %}
    Все рейсы
{% endblock %}

{% block content %}
    {% for fly in flys %}
        <h2>
        <li>
            {{ fly.id }}
            {{ fly.time }}
            <button>
                <a href="{% url 'riddles:fly_detail_url' fly.id %}">Глянуть</a>
            </button>
        </li>

        </h2>
    {% endfor %}
{% endblock %}

Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/templates/riddles/pattern.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>
        {% block title %}
            Из шаблона
        {% endblock %}

    </title>
</head>
<body>
<button>
    <a href="{% url 'riddles:riddles' %}">Главная &nbsp</a>
</button>
<button>
    <a href="{% url 'riddles:fly_list_url' %}">Все полёты &nbsp</a>
</button>
<h1 class="title">
    {% block header %}
    {% endblock %}
</h1>
<p>{% block content %}
{% endblock %}
</p>

</body>
</html>

Kursachh-8d7e9b5798937476966b202e81dd383c8cbe9593/Реализация/untitled1/templates/riddles/riddles.html
{% extends 'riddles/pattern.html' %}
{% block title %}
    Главная
{% endblock %}
{% block header %}
    Заполните форму ниже
{% endblock %}

{% block content %}
    <form action="" method="post"> {% csrf_token %}
      {{ form.as_p }}
    <div>
        <button type="submit">Отправить</button>
    </div>
    </form>

    {% for word in lol %}
        <p>
            {{ word }}
        </p>
    {% endfor %}

    {% for plane in planes %}
        <p>
          <h3>
        {{ plane.name }}
        </h3>


            <li>
            {{ plane.type }}
            </li>

       <button>
       <a href=" {% url 'riddles:air_detail_url' plane.id %}">Посмотреть</a>
       </button>
        </p>



    {% endfor %}
{% endblock %}